### ISSUE TITLE
Incompatibility with node 0.12

### ISSUE THREAD

**Issue by oronbz** [mcavage/node-ldapjs#266] opened 2015-05-15 15:00 UTC
This module is not compatible with node version 0.12

**Comment by lklepner** [comment] 2015-05-21 00:24
In what way? I'm able to search and bind in in 0.12.2.

**Comment by oronbz** [comment] 2015-05-21 05:43
Try to 
npm install ldapjs 
in a brand new folder with node 0.12.x

**Comment by diversario** [comment] 2015-05-22 18:33
I think `dtrace-provider` is what's failing.

**Comment by pfmooney** [comment] 2015-05-25 01:05
This should be fixed in 0.8.  See #270.

**Closed by pfmooney** 2015-05-25 01:05 UTC

**Comment by kenpeter** [comment] 2015-05-26 05:25
i did npm git+https://github.com/mcavage/node-ldapjs.git to get the latest.

**Comment by digicasi** [comment] 2015-06-02 12:01
tried the latest master today... crash is gone... but i get a "502 bad gateway error".
so, doesn't look fixed to me. :-(

**Comment by jsumners** [comment] 2023-03-10 13:56
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
