### ISSUE TITLE
How Do I Catch SizeLimitExceededError When Paging?

### ISSUE THREAD

**Issue by jvanalst** [mcavage/node-ldapjs#308] opened 2015-10-15 22:13 UTC
Ok... I hate to ask this, but I can't for the life of me figure out how to catch this darned SizeLimitExceededError emitted error when doing a search.

The search events bind correctly and I get search results, but neither the 'error' event nor the 'end' event fire before it crashes my application with a throw somewhere obscure deep in events.js.

I thought maybe it was a client level error, and I was indeed able to bind to ```client.on('resultError', cb)``` and capture the error emitted, but it STILL seems to throw somewhere else that's uncatchable.

Any suggestions?

**Comment by jvanalst** [comment] 2015-10-15 23:12
Story of my life. It has something to do with ```paged: true```. If I turn off paging it works just fine and the ```error``` event fires as expected.

**Comment by jvanalst** [comment] 2015-10-15 23:29
Ok... the inconsistency comes from not having a set pageSize value. If you have a manual pageSize you can set it higher then sizeLimit (which you aren't suppose to do), and then the pageControl gets ignored somewhere downstream (semi-expected?).

> Aside: Should the smart default in client.js lines 819-827 allow this situation? E.g. Should that if statement be broken up to not let people do weird things like I inadvertently did?

My actual problem appears to be if it's paged the 'error' event gets passed to a different emitter created in the paging process instead of the ```res``` object in the ```client.search``` callback, and so it goes un-handled no matter what I do. So I'm kind of at a loss.

**Comment by pfmooney** [comment] 2015-10-15 23:49
There's a bug in the paging logic.  Thanks for pointing it out.  I'll try to have a fix pushed later tonight

**Comment by pfmooney** [comment] 2015-10-16 02:52
It should be fixed in c10a1a6faf2765c3742cc0cf3f571cb231e23853

**Comment by jvanalst** [comment] 2015-10-16 15:05
That does indeed resolve the error event never getting fired when paging. Thanks.

**Closed** 2015-10-16 15:06 UTC
Labels: bug

**Comment by jsumners** [comment] 2023-03-10 13:55
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
