### ISSUE TITLE
socket.socket undefined using TLS on Node 0.12.7

### ISSUE THREAD

**Issue by anthony-o** [mcavage/node-ldapjs#289] opened 2015-08-14 09:09 UTC
When trying to connect using `ldapjs.createClient({url: 'ldaps://url.to.ldap.tld:636/'})`, I'm getting this stack on Node 0.12.7:

```
TypeError: Cannot read property 'on' of undefined
    at setupSocket (c:\Users\E0234544\Projets\TM4ALL\node_modules\ldapjs\lib\client\client.js:111:14)
    at Client._connect (c:\Users\E0234544\Projets\TM4ALL\node_modules\ldapjs\lib\client\client.js:742:3)
    at new Client (c:\Users\E0234544\Projets\TM4ALL\node_modules\ldapjs\lib\client\client.js:247:22)
    at Object.createClient (c:\Users\E0234544\Projets\TM4ALL\node_modules\ldapjs\lib\client\index.js:60:12)
```

The code there is:

```js
  // Since tls.socket doesn't emit 'close' events, we must register to receive
  // them on net.socket instead
  var closeSocket = (opts.secure ? socket.socket : socket);
  // On close we have to walk the outstanding messages and go invoke their
  // callback with an error.
  closeSocket.on('close', function onClose(had_err) {
```
`opts.secure` equals to `true` but `socket.socket` doesn't exist (is `undefined`).

Moreover, looking at the [Nodejs `tls.connect()`](https://nodejs.org/api/tls.html#tls_tls_connect_port_host_options_callback) API, I don't understand why a distinction is done between secured (using `tls` API, and calling `socket.socket`) and unsecured (using `net` API and calling directly `socket`) connections.

I'm using node-ldapjs v0.7.1.

**Comment by anthony-o** [comment] 2015-08-14 09:33
Using latest dev version (`"dependencies": {"ldapjs": "mcavage/node-ldapjs#acc1ca8f4314fd9d67561feabc8ce4c235076a5e"}`) fixed this issue.

**Comment by matthew-b-payne** [comment] 2015-08-14 20:02
Yes, I have this issue with any of the node 0.12.x builds.  okay for 0.10.36

**Comment by rochal** [comment] 2015-08-21 00:23
Hi @mcavage, have you got an ETA to cut new release out of master and push to npm? This issue blocking us a bit as we switched to 0.12.

**Comment by pfmooney** [comment] 2015-08-21 06:06
0.8.0 is mostly ready, save for updated documentation.
I have not been able to find time to work on it recently.

**Comment by astanciu** [comment] 2015-08-24 02:19
How were you able to install this on node 0.12. As per Issue #281, didn't think this could be installed...?

**Comment by anthony-o** [comment] 2015-08-24 09:40
I just put `"ldapjs": "mcavage/node-ldapjs#acc1ca8f4314fd9d67561feabc8ce4c235076a5e"` as an npm dependency for my project in my `package.json`.

**Comment by mstorus** [comment] 2015-09-22 18:49
Hi @pfmooney . Thanks for working on this project!
Do you have any estimate on when a new version will be released that includes this fix?

**Comment by pfmooney** [comment] 2015-10-16 04:15
I'm working on finishing updates to the documentation.
When that is done, I'll cut the release.

**Comment by pfmooney** [comment] 2015-10-23 02:27
1.0.0 has been released with updated dependencies

**Closed by pfmooney** 2015-10-23 02:27 UTC

**Comment by umadevisk89** [comment] 2018-05-30 07:34
I get below error  Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:696:11)

**Comment by jsumners** [comment] 2023-03-10 13:55
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
