### ISSUE TITLE
Is this project still alive/maintained?

### ISSUE THREAD

**Issue by jgeurts** [mcavage/node-ldapjs#488] opened 2018-08-15 16:20 UTC
There are open pull requests with no activity from @joyent. Is this project still maintained? If it is active, I apologize. If not, can it be transferred to an organization with members that will be active?

**Comment by tastypackets** [comment] 2018-08-16 15:29
It seems pretty dormant from the time I have been watching it on github. I think it might be time for someone to fork it.

**Comment by Artum** [comment] 2018-08-27 15:49
Did you guys tried to contact the maintainer by email?

**Comment by jgeurts** [comment] 2018-08-27 16:00
That's a good idea. I haven't tried, but I'll give it a shot!

**Comment by melloc** [comment] 2018-08-27 16:58
Hey all! I'm planning on doing a release with the node v6 fixes and some documnetation changes sometime this week. I'll reply here once it's published.

**Comment by melloc** [comment] 2018-08-27 19:36
(Sorry, misread the URL earlier, and thought this was a different ticket. Posting new comment.)

@jgeurts Sorry for the lack of activity lately. I'd planned on taking care of them earlier this year when I transferred the repo, but I've had other things come up, and haven't had the time to fix things correctly. I'm hoping to work my way through them soon. Is there a specific ticket you were looking at?

**Comment by jgeurts** [comment] 2018-08-27 20:35
No worries, I definitely understand how things come up, just didn't want the project to become abandoned. I'm mainly interested in #485. That is preventing us from updating to node v10.

**Comment by purplemana** [comment] 2018-10-11 10:46
The pending PRs are still in wait. It'd be great to see the repo back in action.

**Comment by nytsua** [comment] 2018-11-05 21:48
@joyent Are you looking for people to help with PRs?

**Comment by jvanalst** [comment] 2018-11-05 21:49
I'm with @jgeurts. As soon as #485 is fixed we're in business again. I think that should be the first priority.

**Comment by jgeurts** [comment] 2018-11-05 23:35
I'm not convinced this project is active anymore, unfortunately.

If anyone is interested, I have started working on the https://github.com/ldapts/ldapts project. The goal, aside from adding type information, is to modernize the syntax a bit and fix some outstanding issues. 

It's still very early in development (I'm working on Client first) and I welcome anyone who wants to lend a hand...

**Comment by tastypackets** [comment] 2018-11-06 00:04
@jgeurts I'll be watching your progress, hopefully it will turn into a maintained alternative to ldapjs.

**Comment by acappella2017** [comment] 2018-11-22 08:38
@melloc

Node.js starts LTS for V10 since Oct. 30, can we merge #485 to support Node 10?

**Comment by sunpeinju** [comment] 2018-11-28 00:57
@melloc 

Could you take a look at #497 ? Witch enables Node.js V10 support and all UTs have passed.

**Comment by sunpeinju** [comment] 2018-11-30 00:50
@joyent Could any body help to handle  #497 ?
ldapjs is broken with Node.js V10 and we want to bring it back to live.

**Comment by jgeurts** [comment] 2018-12-10 20:47
If anyone needs node v10+ support, I've been using https://www.npmjs.com/package/ldapts for about the last week to connect to a couple active directories with > 30k users. It has been working well and includes the fixes in #497.

**Comment by hcderaad** [comment] 2019-02-05 09:08
For those looking for a lightweight LDAP server protocol implementation, perhaps this (pure) PHP library is an option worth considering: https://github.com/FreeDSx/LDAP/blob/master/docs/Server/General-Usage.md 
Besides that there is also a Go LDAP client/server implementation: glauth
But for web developers the PHP switch might be a closer call.

**Comment by kspearrin** [comment] 2019-03-22 20:41
2019 now and #485 still hasn't been fixed. Should we just move to ldapts?

**Comment by rienheuver** [comment] 2019-07-09 09:10
@melloc has responded June 22 2019 here: https://github.com/nodejs/package-maintenance/issues/221
Currently at our work we are trying to make a choice for which library to use for our new project. We are building an auth-server in Node and need to also authenticate/authorize with LDAP-servers (Active Directory mostly). However, it's hard to pick a package that we can depend on for maintenance in the future. So hopefully the package will be transferred for maintenance

**Comment by UziTech** [comment] 2019-08-20 14:44
@jsumners since this repo moved to @ldapjs, are we going to see more active development?

I have an active fork at [UziTech/node-ldapjs](https://github.com/UziTech/node-ldapjs) that I have been merging some of the pull requests to.

I have also been trying to update the codebase to use newer ES features and stable dependencies in https://github.com/UziTech/node-ldapjs/pull/2 available at [@uzitech\ldapjs@next](https://www.npmjs.com/package/@uzitech/ldapjs?activeTab=versions)

**Comment by jsumners** [comment] 2019-08-20 15:14
I didn’t realize it had been migrated. I never got an email or anything notifying me. Let me have some time to make sure we can publish things and get the lay of the land so to speak.

**Comment by melloc** [comment] 2019-08-20 16:23
@jsumners I've created an `ldapjs` organization on npm, and invited you to it. I've added the `ldapjs` package to the organization's `developer` team.

**Comment by jsumners** [comment] 2019-08-20 18:28
@melloc 👍

I'll start looking into this stuff soon.

At some point we may want to figure out website stuff, but I'll want to focus first on some package updates.

**Comment by jsumners** [comment] 2019-08-25 01:48
I did a little bit of work tonight merging some low hanging fruit PRs into a new `next` branch. It would be helpful if people could look through PRs and start some new ones to add unit tests to PRs that are likely abandoned and are missing tests.

The priority should be getting the library working on current LTS and Node 12. Then an npm `@next` release can be published and a deprecation notice added to the current latest asking for people to test it out.

**Closed as completed** 2019-08-26 14:05 UTC

**Comment by jsumners** [comment] 2023-03-10 13:51
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
