### ISSUE TITLE
 CERT_UNTRUSTED error 

### ISSUE THREAD

**Issue by yosser22** [mcavage/node-ldapjs#279] opened 2015-07-07 18:21 UTC
Hi everybody,

I'm using node-activedirectory  in order to authenticate user against  AD "ldaps://url" using SSL. (it is using ldapjs as dependency for SSL/TLS negotiation)
the SSL certificate that the domain controller (i.e. Active Directory) is using or returning to me
is signed by a certificate authority that my machine trusts. 
When I test the authentication against the same AD using another application it works perfectly(same certification, same client, same AD, the application is not a nodejs application). 
It means that my machine trusts the certificate authority returned by the AD. (I can also see the certificate on the list of trusted certificates).
So now the problem is that when I try the same in my nodejs application using the node-activedirectory modul, I'm getting a CERT_UNTRUSTED error !!!!
I think that the node-activedirectory doesn't recognize the certification although it is on the list of trusted certifications.
This error is driving me crazy. So if anyone has a suggestion, please help!

Thank you

**Comment by msimerson** [comment] 2015-07-07 21:04
That's because your node.js application doesn't automatically load your trust store. Go have a look at the ca param offered in the [TLS module](https://nodejs.org/api/tls.html) or this [SO question](http://stackoverflow.com/questions/14619576/where-is-the-default-ca-certs-used-in-nodejs).

**Comment by yosser22** [comment] 2015-07-07 21:08
Hey thank you for your help,
I have a question... I have now this code:
var ActiveDirectory = require('activedirectory');
var config = { url: 'ldaps://dc.domain.com',
               baseDN: 'dc=domain,dc=com',
               username: 'username@domain.com',
               password: 'password' }
var ad = new ActiveDirectory(config);

Where do I have to specify the array array of strings or Buffers of trusted certificates in PEM format.
Do you have an explicit example ???

Thank you again

**Comment by msimerson** [comment] 2015-07-07 21:22
I started with the activedirectory module myself, but then couldn't get it to do what I needed, so I just used ldapjs directory. I checked my old ad branch (not merged) and didn't have any SSL/TLS support in there, so that's probably the rock my AD module usage shipwrecked on. I went straight to ldapjs and have been using that instead.

**Closed** 2015-10-27 14:37 UTC
Labels: question

**Comment by jsumners** [comment] 2023-03-10 13:56
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
