### ISSUE TITLE
"pool is shutting down"; 0.8 reliability?

### ISSUE THREAD

**Issue by airandfingers** [mcavage/node-ldapjs#253] opened 2015-02-23 18:44 UTC
We've observed a condition under which our ldapjs client, after an idle period, returns a "pool is shutting down" error, preventing our app from performing any LDAP operations until the app is restarted.

I see that version 0.8 on GitHub has eliminated pools altogether, but this version hasn't been pushed to NPM. Is 0.8 unreliable or untested, or is it production-ready, and it's just been kept off NPM for some other reason?

**Comment by pfmooney** [comment] 2015-02-23 20:11
Since v0.8.0 represents a number of significant changes to the API, I'm not yet comfortable cutting a release.  There are several pieces (like the post-connect client setup API) that deserve additional attention before the interface becomes committed.

**Comment by airandfingers** [comment] 2015-02-24 01:33
Okay, thanks for the clarification.

Could you help me troubleshoot this "pool is shutting down" error? I suspect this error may be caused by improper use of ldapjs and/or improper LDAP configuration.

Here's what I'm doing:

1. Create a single client with
    ```javascript
    client = ldap.createClient({
        url: config.auth.LDAP_SERVER_URL,
        tlsOptions: config.TLS_OPTIONS,
        maxConnections: 10,
        maxIdleTime: 120000,
        checkInterval: 30000
    });
    ```

2. Any time a user attempts to log in, call client.bind with the user's credentials, and allow login if the callback is called without an error; reject login otherwise.

3. Make client.add, .modify, .modifyDN, and .del calls as requested by logged-in users (after checking that users are authorized by use of custom middleware).

4. Never call client.unbind.

**Comment by atiertant** [comment] 2015-03-23 09:44
@airandfingers : i got the same problem with 0.7.1
1. Create a single client with

    ldap.createClient({
       url: url,
       maxConnections: 10
    });

2. Any time a user attempts to log in, call client.bind with the user's credentials.

3. client.search to get user information

4. Never call client.unbind.

and some time i got "pool is shutting down" and i must restart application.

**Comment by pfmooney** [comment] 2015-05-25 01:07
The pooled client is removed in #master and will be absent from 0.8.
Please let me know if your problems persist on the new code.

**Closed by pfmooney** 2015-05-25 01:07 UTC
Labels: question

**Comment by atiertant** [comment] 2015-05-26 07:24
@pfmooney i used https://github.com/coopernurse/node-pool, that's correct my problem

**Comment by jsumners** [comment] 2023-03-10 13:56
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
