### ISSUE TITLE
Disable DTrace dependency

### ISSUE THREAD

**Issue by dimkinv** [mcavage/node-ldapjs#246] opened 2015-01-27 15:27 UTC
Hello,
Lately I start using the ldapjs module and we run into a problem.
The ldapjs requires DTrace installed.
Since I doesn’t have a DTrace installed on my machine (Linux), rpm failed to install.
Is there a way to disable DTrace  requirement?
Please advise how to handle the problem.

Thanks, Yaniv

**Comment by pfmooney** [comment] 2015-01-28 16:58
The dtrace-provider package is marked as an optional dependency.
While there may be errors while installing on a platform without proper dtrace support, the process will ultimately succeed.

**Closed** 2015-02-16 20:07 UTC
Labels: question

**Comment by jsumners** [comment] 2023-03-10 13:56
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
