### ISSUE TITLE
ldapjs@0.7.1 (newest) build fails on node v4.2.1

### ISSUE THREAD

**Issue by qsona** [mcavage/node-ldapjs#309] opened 2015-10-20 04:41 UTC
When I tried to `npm install ldapjs` on node v4.2.1 / npm 3.3.8, many errors about building `dtrace_provider` occured and `dtrace_provider` was not installed.

`fatal error: too many errors emitted, stopping now [-ferror-limit=]`

The dependency is
`ldapjs(0.7.1) => bunyan(0.22.1) => dtrace_provider(0.2.8)`

This problem seems to be solved at the edge of ldapjs because `bunyan` version is new, so I'll happy if it will be released soon. If it will be hard, could you please update only bunyan's version and release it as 0.7.2?

Thanks.

**Comment by pfmooney** [comment] 2015-10-23 02:27
1.0.0 has been released with updated dependencies

**Closed by pfmooney** 2015-10-23 02:27 UTC

**Comment by qsona** [comment] 2015-10-23 03:24
Thank you.

**Comment by jsumners** [comment] 2023-03-10 13:55
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
