### ISSUE TITLE
Non ascii characters in filter not working in client search

### ISSUE THREAD

**Issue by jimmyengman** [mcavage/node-ldapjs#936] opened 2023-08-15 16:55 UTC
If I start an OpenLDAP docker container as suggested in https://github.com/ldapjs/docker-test-openldap and then connect to it with ldap.createClient I can search with filter sn=Conrad and get a searchEntry for Hermes Conrad printed but when I search for sn=Rodríguez no entry is found. 

import { default as ldap } from 'ldapjs';

// ************ if this opts are used an entry will be printed ************
// const opts = {
//   filter: '(&(sn=Conrad)',
//   scope: 'sub',
//   attributes: ['dn', 'sn', 'cn'],
//   type: 'user'
// };

// ************ using this opts no entry is found *****************
const opts = {
  filter: '(&(sn=Rodríguez)',
  scope: 'sub',
  attributes: ['dn', 'sn', 'cn'],
  type: 'user'
};

client.search('dc=planetexpress,dc=com', opts, (err, res) => {

  res.on('searchRequest', (searchRequest) => {
    console.log('searchRequest: ', searchRequest.messageId);
  });
  res.on('searchEntry', (entry) => {
    console.log('entry: ' + JSON.stringify(entry.pojo));
  });
  res.on('searchReference', (referral) => {
    console.log('referral: ' + referral.uris.join());
  });
  res.on('error', (err) => {
    console.error('error: ' + err.message);
  });
  res.on('end', (result) => {
    console.log('status: ' + result.status);
  });
});

**Comment by jsumners** [comment] 2023-08-15 19:33
Duplicate of #860. Please review that issue.

**Closed as not planned by jsumners** 2023-08-15 19:33 UTC
